version: "3"

services:
    acra-server:
        image: "cossacklabs/acra-server:${ACRA_DOCKER_IMAGE_TAG:-latest}"
        # Restart server after correct termination, for example after the config
        # was changed through the API
        restart: always
        ports:
            - "3306:3306"
        networks:
            - mutillidae-acraserver
        environment:
            ACRA_MASTER_KEY: ${ACRA_MASTER_KEY:-UHZ3VUNNeTJ0SEFhbWVjNkt4eDdVYkc2WnNpUTlYa0E=}
        volumes:
            # Directory with configuration, rewriteable
            - ./.acraconfigs/acra-server:/config
        command: >-
            --mysql_enable
            --db_host=mutillidae
            --db_port=3306
            --acraconnector_transport_encryption_disable
            --acracensor_config_file=/config/acra-censor.yaml
            --incoming_connection_string=tcp://0.0.0.0:3306
            --client_id=no_matter_id
            -v

    #===== OWASP Mutillidae II =================================================

    edoz90_mutillidae:
        # Build base image from edoz90/docker-mutillidae
        build:
            context: https://github.com/edoz90/docker-mutillidae.git
        image: edoz90_mutillidae:latest
        # We don't need to run the container based on the original image
        entrypoint: /bin/true
        restart: 'no'


    mutillidae:
        depends_on:
            - edoz90_mutillidae
        build:
            context: ./mutillidae
        image: mutillidae:latest
        ports:
            - "8080:80"
            - "3306:3306"
        networks:
            - world
            - mutillidae-acraserver


networks:
    world:
    mutillidae-acraserver:
        internal: true
